version: "3.1"

services:
  scheduler_cpu:
#    build:
#      context: ./base
#      dockerfile: Dockerfile
    image: celsiustx/rightsize_99_standard_py37
    hostname: dask-scheduler-cpu
    ports:
      - "18786:8786"
      - "18787:8787"
    command: ["dask-scheduler"]

  scheduler_gpu:
    #    build:
    #      context: ./base
    #      dockerfile: Dockerfile
    image: celsiustx/rightsize_99_standard_py37
    hostname: dask-scheduler-gpu
    ports:
      - "28786:8786"
      - "28787:8787"
    command: ["dask-scheduler"]

  worker_cpu_1:
#    build:
#      context: ./base
#      dockerfile: Dockerfile
#    image: daskdev/dask
    image: celsiustx/rightsize_99_standard_py37
    hostname: dask-worker-cpu-1
    command: ["dask-worker", "tcp://scheduler_cpu:8786", "--name", "worker-cpu-1"]

  worker_cpu_2:
    image: celsiustx/rightsize_99_standard_py37
    hostname: dask-worker-cpu-2
    command: ["dask-worker", "tcp://scheduler_cpu:8786", "--name", "worker-cpu-2"]

  worker_gpu_1:
    image: celsiustx/rightsize_99_standard_py37
    hostname: dask-worker-gpu-1
    command: ["dask-worker", "tcp://scheduler_gpu:8786", "--name", "worker-gpu-1"]

  worker_gpu_2:
    image: celsiustx/rightsize_99_standard_py37
    hostname: dask-worker-gpu-2
    command: ["dask-worker", "tcp://scheduler_gpu:8786", "--name", "worker-gpu-2"]


#  base-notebook:
#    build:
#      context: github.com/jupyter/docker-stacks.git#master:base-notebook
#      dockerfile: Dockerfile
#      args:
#        PYTHON_VERSION: "3.7"
#    image: jupyter/base-notebook:lab
#
#  notebook:
#    build:
#      context: ./notebook
#      dockerfile: Dockerfile
#    image: daskdev/dask-notebook
#    depends_on:
#      - base-notebook
#    hostname: notebook
#    ports:
#      - "8888:8888"
#    environment:
#      - DASK_SCHEDULER_ADDRESS="tcp://scheduler:8786"
